### ISSUE TITLE
Svona hegðun er ekki í lagi

### ISSUE THREAD

**Issue by joningi98** [BjarkiF/MAPP-toodler#2]
https://github.com/BjarkiF/MAPP-toodler/blob/471165ff289fc469ee7f613af7830662beaf9395/toodler/src/components/BookItem/index.jsx#L19

**Comment by einarprump** [comment]
Mér finnst þetta allt í lagi, það er í lagi að hafa samfarir við eitthvað rangt.

**Comment by BjarkiF** [comment]
Jón láttu mig vera

**Comment by joningi98** [comment]
Vá aldeilis móktur hérna, skal loka þessu issue þá
